# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgregadorCourseWorks_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(40)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setMinimumSize(QtCore.QSize(400, 150))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setMinimumSize(QtCore.QSize(40, 50))
        self.label_8.setMaximumSize(QtCore.QSize(50, 50))
        self.label_8.setBaseSize(QtCore.QSize(40, 50))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.bel_nombreCurso = QtWidgets.QLabel(self.widget_3)
        self.bel_nombreCurso.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_nombreCurso.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_nombreCurso.setBaseSize(QtCore.QSize(200, 50))
        self.bel_nombreCurso.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_nombreCurso.setObjectName("bel_nombreCurso")
        self.horizontalLayout_10.addWidget(self.bel_nombreCurso)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setMinimumSize(QtCore.QSize(40, 50))
        self.label_9.setMaximumSize(QtCore.QSize(50, 50))
        self.label_9.setBaseSize(QtCore.QSize(40, 50))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.bel_nombreTopic = QtWidgets.QLabel(self.widget_3)
        self.bel_nombreTopic.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_nombreTopic.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_nombreTopic.setBaseSize(QtCore.QSize(200, 50))
        self.bel_nombreTopic.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_nombreTopic.setObjectName("bel_nombreTopic")
        self.horizontalLayout_11.addWidget(self.bel_nombreTopic)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_9.addWidget(self.widget_3)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_refrescarCourseWorks = QtWidgets.QPushButton(Dialog)
        self.btn_refrescarCourseWorks.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_refrescarCourseWorks.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_refrescarCourseWorks.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_refrescarCourseWorks.setBaseSize(QtCore.QSize(30, 30))
        self.btn_refrescarCourseWorks.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/cargar_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
"}\n"
"")
        self.btn_refrescarCourseWorks.setText("")
        self.btn_refrescarCourseWorks.setObjectName("btn_refrescarCourseWorks")
        self.verticalLayout_13.addWidget(self.btn_refrescarCourseWorks)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setMinimumSize(QtCore.QSize(40, 30))
        self.label_13.setMaximumSize(QtCore.QSize(50, 50))
        self.label_13.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 160))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Clase:"))
        self.bel_nombreCurso.setText(_translate("Dialog", "Python pre-intermedio"))
        self.label_9.setText(_translate("Dialog", "Topic:"))
        self.bel_nombreTopic.setText(_translate("Dialog", "Python pre-intermedio"))
        self.label_13.setText(_translate("Dialog", "Cargar "))
        self.label_2.setText(_translate("Dialog", "Asignaciones:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Fecha creacion"))
import img_rc
