# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizadorTareas_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 572)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(400, 150))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 18))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.btn_editarClase = QtWidgets.QPushButton(self.widget)
        self.btn_editarClase.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_editarClase.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editarClase.setBaseSize(QtCore.QSize(18, 18))
        self.btn_editarClase.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/edit_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
"}\n"
"")
        self.btn_editarClase.setText("")
        self.btn_editarClase.setObjectName("btn_editarClase")
        self.horizontalLayout_3.addWidget(self.btn_editarClase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(40, 50))
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setBaseSize(QtCore.QSize(40, 50))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.bel_nombreCurso = QtWidgets.QLabel(self.widget)
        self.bel_nombreCurso.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_nombreCurso.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_nombreCurso.setBaseSize(QtCore.QSize(200, 50))
        self.bel_nombreCurso.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_nombreCurso.setObjectName("bel_nombreCurso")
        self.horizontalLayout_2.addWidget(self.bel_nombreCurso)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_refrescarTodasTareas = QtWidgets.QPushButton(Form)
        self.btn_refrescarTodasTareas.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_refrescarTodasTareas.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_refrescarTodasTareas.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_refrescarTodasTareas.setBaseSize(QtCore.QSize(30, 30))
        self.btn_refrescarTodasTareas.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/cargar_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
"}\n"
"")
        self.btn_refrescarTodasTareas.setText("")
        self.btn_refrescarTodasTareas.setObjectName("btn_refrescarTodasTareas")
        self.verticalLayout_2.addWidget(self.btn_refrescarTodasTareas)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(30, 30))
        self.label_11.setMaximumSize(QtCore.QSize(50, 50))
        self.label_11.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_agregarTarea = QtWidgets.QPushButton(Form)
        self.btn_agregarTarea.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_agregarTarea.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_agregarTarea.setBaseSize(QtCore.QSize(30, 30))
        self.btn_agregarTarea.setStyleSheet("\n"
"QPushButton {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/plus_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
"}\n"
"")
        self.btn_agregarTarea.setText("")
        self.btn_agregarTarea.setObjectName("btn_agregarTarea")
        self.verticalLayout.addWidget(self.btn_agregarTarea)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(30, 30))
        self.label_12.setMaximumSize(QtCore.QSize(50, 50))
        self.label_12.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Clase:"))
        self.bel_nombreCurso.setText(_translate("Form", "Python pre-intermedio"))
        self.label_11.setText(_translate("Form", "Cargar "))
        self.label_12.setText(_translate("Form", "Nueva tarea"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Fecha creacion"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Calificadas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Por calificar"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Sin entregar"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Promedio"))
import img_rc
