# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistroPregunta_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 539)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMinimumSize(QtCore.QSize(320, 70))
        self.label_12.setMaximumSize(QtCore.QSize(310, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(85, 0, 127);\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_infoDudas = QtWidgets.QPushButton(Dialog)
        self.btn_infoDudas.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_infoDudas.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_infoDudas.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border-image: url(:/main/IMAGENES/info_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/main/IMAGENES/info_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/main/IMAGENES/info_off.png);\n"
"}")
        self.btn_infoDudas.setText("")
        self.btn_infoDudas.setObjectName("btn_infoDudas")
        self.verticalLayout.addWidget(self.btn_infoDudas)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMinimumSize(QtCore.QSize(25, 25))
        self.label_11.setMaximumSize(QtCore.QSize(25, 25))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(150, 50))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_nombreTarea = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nombreTarea.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_nombreTarea.setBaseSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lineEdit_nombreTarea.setFont(font)
        self.lineEdit_nombreTarea.setMaxLength(20)
        self.lineEdit_nombreTarea.setObjectName("lineEdit_nombreTarea")
        self.horizontalLayout.addWidget(self.lineEdit_nombreTarea)
        self.btn_info_nombre = QtWidgets.QPushButton(Dialog)
        self.btn_info_nombre.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_info_nombre.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_info_nombre.setStyleSheet("QPushButton{\n"
"    border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        border-image: url(:/main/IMAGENES/tache_on.png);\n"
"}\n"
"QPushButton:pressed{\n"
"        border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}")
        self.btn_info_nombre.setText("")
        self.btn_info_nombre.setObjectName("btn_info_nombre")
        self.horizontalLayout.addWidget(self.btn_info_nombre)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_urlSoloLectura = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_urlSoloLectura.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_urlSoloLectura.setBaseSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lineEdit_urlSoloLectura.setFont(font)
        self.lineEdit_urlSoloLectura.setMaxLength(20)
        self.lineEdit_urlSoloLectura.setObjectName("lineEdit_urlSoloLectura")
        self.horizontalLayout_4.addWidget(self.lineEdit_urlSoloLectura)
        self.btn_info_urlSoloLectura = QtWidgets.QPushButton(Dialog)
        self.btn_info_urlSoloLectura.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_info_urlSoloLectura.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_info_urlSoloLectura.setStyleSheet("QPushButton{\n"
"    border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        border-image: url(:/main/IMAGENES/tache_on.png);\n"
"}\n"
"QPushButton:pressed{\n"
"        border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}")
        self.btn_info_urlSoloLectura.setText("")
        self.btn_info_urlSoloLectura.setObjectName("btn_info_urlSoloLectura")
        self.horizontalLayout_4.addWidget(self.btn_info_urlSoloLectura)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setMinimumSize(QtCore.QSize(150, 50))
        self.label_20.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.lineEdit_idArchivo = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_idArchivo.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_idArchivo.setBaseSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lineEdit_idArchivo.setFont(font)
        self.lineEdit_idArchivo.setMaxLength(20)
        self.lineEdit_idArchivo.setObjectName("lineEdit_idArchivo")
        self.horizontalLayout_7.addWidget(self.lineEdit_idArchivo)
        self.btn_info_id_archivo = QtWidgets.QPushButton(Dialog)
        self.btn_info_id_archivo.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_info_id_archivo.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_info_id_archivo.setStyleSheet("QPushButton{\n"
"    border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        border-image: url(:/main/IMAGENES/tache_on.png);\n"
"}\n"
"QPushButton:pressed{\n"
"        border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}")
        self.btn_info_id_archivo.setText("")
        self.btn_info_id_archivo.setObjectName("btn_info_id_archivo")
        self.horizontalLayout_7.addWidget(self.btn_info_id_archivo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(150, 60))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setBaseSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.textEdit_indicaciones = QtWidgets.QTextEdit(Dialog)
        self.textEdit_indicaciones.setMinimumSize(QtCore.QSize(300, 60))
        self.textEdit_indicaciones.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_indicaciones.setSizeIncrement(QtCore.QSize(0, 0))
        self.textEdit_indicaciones.setBaseSize(QtCore.QSize(300, 60))
        self.textEdit_indicaciones.setObjectName("textEdit_indicaciones")
        self.horizontalLayout_3.addWidget(self.textEdit_indicaciones)
        self.btn_info_indicaciones = QtWidgets.QPushButton(Dialog)
        self.btn_info_indicaciones.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_info_indicaciones.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_info_indicaciones.setStyleSheet("QPushButton{\n"
"    border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        border-image: url(:/main/IMAGENES/tache_on.png);\n"
"}\n"
"QPushButton:pressed{\n"
"        border-image: url(:/main/IMAGENES/tache_off.png);\n"
"}")
        self.btn_info_indicaciones.setText("")
        self.btn_info_indicaciones.setObjectName("btn_info_indicaciones")
        self.horizontalLayout_3.addWidget(self.btn_info_indicaciones)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.btn_asignarTarea = QtWidgets.QCommandLinkButton(Dialog)
        self.btn_asignarTarea.setMinimumSize(QtCore.QSize(170, 0))
        self.btn_asignarTarea.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.btn_asignarTarea.setFont(font)
        self.btn_asignarTarea.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("?")
        self.btn_asignarTarea.setIcon(icon)
        self.btn_asignarTarea.setObjectName("btn_asignarTarea")
        self.horizontalLayout_6.addWidget(self.btn_asignarTarea)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_12.setText(_translate("Dialog", "Creacion tarea:"))
        self.label_3.setText(_translate("Dialog", "Nombre:"))
        self.label_10.setText(_translate("Dialog", "URL solo lectura:"))
        self.label_20.setText(_translate("Dialog", "ID archivo"))
        self.label_9.setText(_translate("Dialog", "Indicaciones:"))
        self.label_4.setText(_translate("Dialog", "l"))
        self.btn_asignarTarea.setText(_translate("Dialog", "Asignar tarea"))
import img_rc
