# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualizadorTareas_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 467)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, -1)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_refrescarTodasTareas = QtWidgets.QPushButton(Form)
        self.btn_refrescarTodasTareas.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_refrescarTodasTareas.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_refrescarTodasTareas.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_refrescarTodasTareas.setBaseSize(QtCore.QSize(30, 30))
        self.btn_refrescarTodasTareas.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/cargar_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/cargar_off.png);\n"
"}\n"
"")
        self.btn_refrescarTodasTareas.setText("")
        self.btn_refrescarTodasTareas.setObjectName("btn_refrescarTodasTareas")
        self.verticalLayout_2.addWidget(self.btn_refrescarTodasTareas)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(30, 30))
        self.label_11.setMaximumSize(QtCore.QSize(50, 50))
        self.label_11.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_agregarTarea = QtWidgets.QPushButton(Form)
        self.btn_agregarTarea.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_agregarTarea.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_agregarTarea.setBaseSize(QtCore.QSize(30, 30))
        self.btn_agregarTarea.setStyleSheet("\n"
"QPushButton {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/plus_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
"}\n"
"")
        self.btn_agregarTarea.setText("")
        self.btn_agregarTarea.setObjectName("btn_agregarTarea")
        self.verticalLayout.addWidget(self.btn_agregarTarea)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(30, 30))
        self.label_12.setMaximumSize(QtCore.QSize(50, 50))
        self.label_12.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "Cargar "))
        self.label_12.setText(_translate("Form", "Nueva tarea"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Fecha creacion"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Calificadas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Por calificar"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Sin entregar"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Promedio"))
import img_rc
