# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CambiadorCarpetaDrive_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(352, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bel_tipoClase = QtWidgets.QLabel(Dialog)
        self.bel_tipoClase.setMinimumSize(QtCore.QSize(100, 40))
        self.bel_tipoClase.setMaximumSize(QtCore.QSize(100, 40))
        self.bel_tipoClase.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_tipoClase.setWordWrap(True)
        self.bel_tipoClase.setObjectName("bel_tipoClase")
        self.horizontalLayout.addWidget(self.bel_tipoClase)
        self.bel_nombreCarpetaActual = QtWidgets.QLabel(Dialog)
        self.bel_nombreCarpetaActual.setMinimumSize(QtCore.QSize(200, 40))
        self.bel_nombreCarpetaActual.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bel_nombreCarpetaActual.setStyleSheet("border: 2px solid balck;\n"
"border-radius:5px;")
        self.bel_nombreCarpetaActual.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_nombreCarpetaActual.setObjectName("bel_nombreCarpetaActual")
        self.horizontalLayout.addWidget(self.bel_nombreCarpetaActual)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(300, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.plainText_idCarpeta = QtWidgets.QPlainTextEdit(Dialog)
        self.plainText_idCarpeta.setMinimumSize(QtCore.QSize(150, 50))
        self.plainText_idCarpeta.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainText_idCarpeta.setFont(font)
        self.plainText_idCarpeta.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainText_idCarpeta.setObjectName("plainText_idCarpeta")
        self.horizontalLayout_4.addWidget(self.plainText_idCarpeta)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.btn_realizarCambio = QtWidgets.QPushButton(Dialog)
        self.btn_realizarCambio.setMinimumSize(QtCore.QSize(120, 50))
        self.btn_realizarCambio.setMaximumSize(QtCore.QSize(150, 60))
        self.btn_realizarCambio.setObjectName("btn_realizarCambio")
        self.horizontalLayout_2.addWidget(self.btn_realizarCambio)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bel_tipoClase.setText(_translate("Dialog", "CarpetaActual:"))
        self.bel_nombreCarpetaActual.setText(_translate("Dialog", "Ninguna seleccionada"))
        self.label_3.setText(_translate("Dialog", "Ingresa el id de la carpeta en donde se adjuntaran todas  las retroalimentaciones"))
        self.label.setText(_translate("Dialog", "Id carpeta:"))
        self.btn_realizarCambio.setText(_translate("Dialog", "Realizar cambio"))
import img_rc
