# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CambiadorClases_NbGrader_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 358)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(100, 40))
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bel_nombreClaseActual = QtWidgets.QLabel(Dialog)
        self.bel_nombreClaseActual.setMinimumSize(QtCore.QSize(200, 40))
        self.bel_nombreClaseActual.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bel_nombreClaseActual.setStyleSheet("border: 2px solid balck;\n"
"border-radius:5px;")
        self.bel_nombreClaseActual.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_nombreClaseActual.setObjectName("bel_nombreClaseActual")
        self.horizontalLayout.addWidget(self.bel_nombreClaseActual)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(300, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.comboBox_clases = QtWidgets.QComboBox(Dialog)
        self.comboBox_clases.setMinimumSize(QtCore.QSize(200, 40))
        self.comboBox_clases.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_clases.setObjectName("comboBox_clases")
        self.comboBox_clases.addItem("")
        self.comboBox_clases.addItem("")
        self.comboBox_clases.addItem("")
        self.comboBox_clases.addItem("")
        self.comboBox_clases.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_clases)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.btn_realizarCambio = QtWidgets.QPushButton(Dialog)
        self.btn_realizarCambio.setMinimumSize(QtCore.QSize(120, 50))
        self.btn_realizarCambio.setMaximumSize(QtCore.QSize(150, 60))
        self.btn_realizarCambio.setObjectName("btn_realizarCambio")
        self.horizontalLayout_2.addWidget(self.btn_realizarCambio)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Clase Nb_grader actual: "))
        self.bel_nombreClaseActual.setText(_translate("Dialog", "Ninguna seleccionada"))
        self.label_3.setText(_translate("Dialog", "Selecciona la nueva clase a la cual deseas cambiar:"))
        self.comboBox_clases.setItemText(0, _translate("Dialog", "HOLA"))
        self.comboBox_clases.setItemText(1, _translate("Dialog", "COMO"))
        self.comboBox_clases.setItemText(2, _translate("Dialog", "ESTAS"))
        self.comboBox_clases.setItemText(3, _translate("Dialog", "MI"))
        self.comboBox_clases.setItemText(4, _translate("Dialog", "NOMBRE"))
        self.btn_realizarCambio.setText(_translate("Dialog", "Realizar cambio"))
import img_rc
