# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfiguracionMain_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 602)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(150, 50))
        self.label_9.setMaximumSize(QtCore.QSize(70, 50))
        self.label_9.setBaseSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.bel_nombreClase_classroom = QtWidgets.QLabel(Form)
        self.bel_nombreClase_classroom.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_nombreClase_classroom.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_nombreClase_classroom.setBaseSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bel_nombreClase_classroom.setFont(font)
        self.bel_nombreClase_classroom.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_nombreClase_classroom.setObjectName("bel_nombreClase_classroom")
        self.horizontalLayout_8.addWidget(self.bel_nombreClase_classroom)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_editarClase_classroom = QtWidgets.QPushButton(Form)
        self.btn_editarClase_classroom.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_editarClase_classroom.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editarClase_classroom.setBaseSize(QtCore.QSize(20, 20))
        self.btn_editarClase_classroom.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/edit_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
"}\n"
"")
        self.btn_editarClase_classroom.setText("")
        self.btn_editarClase_classroom.setObjectName("btn_editarClase_classroom")
        self.verticalLayout_9.addWidget(self.btn_editarClase_classroom)
        self.bel_agregar_or_guardar_apar_3 = QtWidgets.QLabel(Form)
        self.bel_agregar_or_guardar_apar_3.setMinimumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_3.setMaximumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_3.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.bel_agregar_or_guardar_apar_3.setFont(font)
        self.bel_agregar_or_guardar_apar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_agregar_or_guardar_apar_3.setWordWrap(True)
        self.bel_agregar_or_guardar_apar_3.setObjectName("bel_agregar_or_guardar_apar_3")
        self.verticalLayout_9.addWidget(self.bel_agregar_or_guardar_apar_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(150, 50))
        self.label_11.setMaximumSize(QtCore.QSize(70, 50))
        self.label_11.setBaseSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.bel_clase_nombreNbGrader = QtWidgets.QLabel(Form)
        self.bel_clase_nombreNbGrader.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_clase_nombreNbGrader.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_clase_nombreNbGrader.setBaseSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bel_clase_nombreNbGrader.setFont(font)
        self.bel_clase_nombreNbGrader.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_clase_nombreNbGrader.setObjectName("bel_clase_nombreNbGrader")
        self.horizontalLayout_9.addWidget(self.bel_clase_nombreNbGrader)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_editarClase_NbGrader = QtWidgets.QPushButton(Form)
        self.btn_editarClase_NbGrader.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_editarClase_NbGrader.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editarClase_NbGrader.setBaseSize(QtCore.QSize(20, 20))
        self.btn_editarClase_NbGrader.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/edit_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
"}\n"
"")
        self.btn_editarClase_NbGrader.setText("")
        self.btn_editarClase_NbGrader.setObjectName("btn_editarClase_NbGrader")
        self.verticalLayout_10.addWidget(self.btn_editarClase_NbGrader)
        self.bel_agregar_or_guardar_apar_4 = QtWidgets.QLabel(Form)
        self.bel_agregar_or_guardar_apar_4.setMinimumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_4.setMaximumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_4.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.bel_agregar_or_guardar_apar_4.setFont(font)
        self.bel_agregar_or_guardar_apar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_agregar_or_guardar_apar_4.setWordWrap(True)
        self.bel_agregar_or_guardar_apar_4.setObjectName("bel_agregar_or_guardar_apar_4")
        self.verticalLayout_10.addWidget(self.bel_agregar_or_guardar_apar_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(150, 50))
        self.label_8.setMaximumSize(QtCore.QSize(70, 50))
        self.label_8.setBaseSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.bel_nombreCarpetaDriveMadre = QtWidgets.QLabel(Form)
        self.bel_nombreCarpetaDriveMadre.setMinimumSize(QtCore.QSize(200, 50))
        self.bel_nombreCarpetaDriveMadre.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bel_nombreCarpetaDriveMadre.setBaseSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bel_nombreCarpetaDriveMadre.setFont(font)
        self.bel_nombreCarpetaDriveMadre.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_nombreCarpetaDriveMadre.setObjectName("bel_nombreCarpetaDriveMadre")
        self.horizontalLayout_7.addWidget(self.bel_nombreCarpetaDriveMadre)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_editarCarpetaMadre = QtWidgets.QPushButton(Form)
        self.btn_editarCarpetaMadre.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_editarCarpetaMadre.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editarCarpetaMadre.setBaseSize(QtCore.QSize(20, 20))
        self.btn_editarCarpetaMadre.setStyleSheet("QPushButton {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/edit_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/edit_off.png);\n"
"}\n"
"")
        self.btn_editarCarpetaMadre.setText("")
        self.btn_editarCarpetaMadre.setObjectName("btn_editarCarpetaMadre")
        self.verticalLayout_8.addWidget(self.btn_editarCarpetaMadre)
        self.bel_agregar_or_guardar_apar_2 = QtWidgets.QLabel(Form)
        self.bel_agregar_or_guardar_apar_2.setMinimumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_2.setMaximumSize(QtCore.QSize(35, 20))
        self.bel_agregar_or_guardar_apar_2.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.bel_agregar_or_guardar_apar_2.setFont(font)
        self.bel_agregar_or_guardar_apar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_agregar_or_guardar_apar_2.setWordWrap(True)
        self.bel_agregar_or_guardar_apar_2.setObjectName("bel_agregar_or_guardar_apar_2")
        self.verticalLayout_8.addWidget(self.bel_agregar_or_guardar_apar_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 18))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_agregarApartado = QtWidgets.QPushButton(Form)
        self.btn_agregarApartado.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_agregarApartado.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_agregarApartado.setBaseSize(QtCore.QSize(30, 30))
        self.btn_agregarApartado.setStyleSheet("\n"
"QPushButton {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/main/IMAGENES/plus_on.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/main/IMAGENES/plus_off.png);\n"
"}\n"
"")
        self.btn_agregarApartado.setText("")
        self.btn_agregarApartado.setObjectName("btn_agregarApartado")
        self.verticalLayout_2.addWidget(self.btn_agregarApartado)
        self.bel_agregar_or_guardar_apar = QtWidgets.QLabel(Form)
        self.bel_agregar_or_guardar_apar.setMinimumSize(QtCore.QSize(35, 35))
        self.bel_agregar_or_guardar_apar.setMaximumSize(QtCore.QSize(35, 35))
        self.bel_agregar_or_guardar_apar.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.bel_agregar_or_guardar_apar.setFont(font)
        self.bel_agregar_or_guardar_apar.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_agregar_or_guardar_apar.setWordWrap(True)
        self.bel_agregar_or_guardar_apar.setObjectName("bel_agregar_or_guardar_apar")
        self.verticalLayout_2.addWidget(self.bel_agregar_or_guardar_apar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tablaWidget_topics_selec = QtWidgets.QTableWidget(Form)
        self.tablaWidget_topics_selec.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tablaWidget_topics_selec.setFont(font)
        self.tablaWidget_topics_selec.setObjectName("tableWidget")
        self.tablaWidget_topics_selec.setColumnCount(1)
        self.tablaWidget_topics_selec.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaWidget_topics_selec.setHorizontalHeaderItem(0, item)
        self.verticalLayout_3.addWidget(self.tablaWidget_topics_selec)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Clase:"))
        self.bel_nombreClase_classroom.setText(_translate("Form", "Python pre-intermedio"))
        self.bel_agregar_or_guardar_apar_3.setText(_translate("Form", "Editar"))
        self.label_11.setText(_translate("Form", "Nb_grader:"))
        self.bel_clase_nombreNbGrader.setText(_translate("Form", "Python pre-intermedio"))
        self.bel_agregar_or_guardar_apar_4.setText(_translate("Form", "Editar"))
        self.label_8.setText(_translate("Form", "Drive dir:"))
        self.bel_nombreCarpetaDriveMadre.setText(_translate("Form", "Python pre-intermedio"))
        self.bel_agregar_or_guardar_apar_2.setText(_translate("Form", "Editar"))
        self.label_6.setText(_translate("Form", "Topic:"))
        self.bel_agregar_or_guardar_apar.setText(_translate("Form", "Importar\n"
"apartado"))
        item = self.tablaWidget_topics_selec.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Topic programas"))
import img_rc
